init -1000 python:

    prologue_loc_pol = {

"Ты снова на задание?" : '''Znowu wyruszasz na misję?''',
"Да. И на этот раз я не могу дать сроков." : '''Tak, i tym razem nie wiem kiedy wrócę.''',
"Это что-то очень серьёзное?" : '''Czy to coś poważnego?''',
"Это всегда очень серьёзно." : '''To zawsze jest coś poważnego.''',
"Но ты же говорил, что выйдешь на пенсию пораньше." : '''Ale przecież mówiłeś, że przejdziesz na wczesną emeryturę.''',
"Так и будет. Это последняя командировка. Я обещаю." : '''I tak zrobię. To moja ostatnia podróż biznesowa. Obiecuję.''',
"Больше я вас не покину." : '''To ostatni raz, kiedy cię zostawiam.''',
"[1]" : "[1]",
"Про меня можешь не волноваться. Волнуйся за свою жену." : '''O mnie nie musisz się martwić. Pomyśl o swojej żonie.''',
"Так ты присмотришь за Мариной?" : '''Zaopiekujesz się Mary?''',
"А у меня есть выбор?" : '''A mam jakiś wybór?''',
"Спасибо, брат. Я знал, что могу положиться на тебя." : '''Dzięki, braciszku. Wiedziałem, że mogę na tobie polegać.''',
"[2]" : "[2]",
"И да, не вздумай влезать в мутные истории. Иначе моему возвращению ты рад не будешь." : '''Jeszcze jedno, trzymaj się z dala od szemranych interesów. W przeciwnym wypadku raczej nie będziesz szczęśliwy na mój widok.''',
"Эй, хочешь, чтобы я заботился о твоей жене, но при этом не доверяешь мне?" : '''Hej, mam pilnować twojej żony i jednocześnie mi nie ufasz?''',
"Просто не подведи меня, брат." : '''Po prostu mnie nie rozczaruj, braciszku.''',
"Удачи…" : '''Powodzenia...''',
"Брат…" : '''Bracie...''',
"[3]" : "[3]",
"Тяжело не чувствовать себя куском говна,\nкогда твой старший брат крутой супер-агент на службе у правительства,\nа ты – обычный парень без каких-либо талантов." : '''Ciężko nie czuć się jak sterta gówna, \nkiedy twój brat jest zajebistym superagentem na usługach rządu, \na ty jesteś zwykłym gościem bez jakiegokolwiek talentu.''',
"Понимая, что у меня никогда в жизни не получиться\nвзобраться так же высоко, я решил рыть вниз." : '''Wiedząc, że nigdy nie wespnę się na wyżyny \njak mój brat, postanowiłem zejść na niższy poziom.''',
"[4]" : "[4]",
"Продажа наркотиков, шулерство, поиск должников и хорошие,\nкак мне казалось, знакомства из криминального мира." : '''Sprzedając dragi, oszukując, szukając dłużników i tworząc, \na przynajmniej tak mi się wtedy wydawało, dobre znajomości w kryminalnym półświatku.''',
"Я не был отпетым бандитом,\nкоторый грабил или обманывал работяг." : '''Nie byłem jakimś totalnym zbirem, \nco by okradał lub oszukiwał zwykłych ludzi.''',
"Как бы смешно это не звучало, но я старался придерживаться морального кодекса." : '''Może to brzmieć zabawnie, ale starałem się trzymać mojego moralnego kodu.''',
"Свои грязные деньги я зарабатывал на таком же дерьме, как и я сам." : '''Całą moją brudną forsę zarobiłem na chujowych ludziach, takich jak ja.''',
"И в какой-то момент, данный маршрут завёл меня в тупик…" : '''W którymś momencie ta droga zaprowadziła mnie do ślepego zaułka...''',
"[5]" : "[5]",
"Те деньги, что брат оставил мне на время своего отсутствия,\nя проиграл в спортивном тотализаторе спустя неделю." : '''Pieniądze, które mój brat zostawił na czas gdy go nie ma, \nzostały przeze mnie stracone na zakładach sportowych.''',
"И чтобы не вымаливать у Марины мелочь на карманные расходы,\nя решил быстро подзаработать." : '''A że nie chciałem zawracać głowy Mary i prosić \nją o drobniaki,\npostanowiłem zarobić pieniądze, i to szybko.''',
"[6]" : "[6]",
"Мой хороший друг Игорь (сын русских эмигрантов),\nнашёл каких-то простаков для игры в покер. Лёгкие деньги." : '''Mój dobry przyjaciel Igor (syn Rosyjskich imigrantów)\n\nznalazł jakichś frajerów na parę rundek pokera. Łatwy szmal.''',
"Так называемые «простачки» оказались детьми местных чиновников,\nа чиновники, в свою очередь, были компаньонами бандита по кличке «Жлоб». Короче говоря, люди непростые." : '''Ci tak zwani "frajerzy" okazali się być dzieciakami lokalnych rządzących,\n a ci\nbyli kompanami gangstera \no ksywie "Sting". W skrócie, byli oni skomplikowanymi ludźmi.''',
"Друзья «Жлоба» играли на редкость плохо. Дилетанты." : '''Kumple "Stinga" grali naprawdę tragicznie. \nAmatorzy.''',
"[7]" : "[7]",
"Мы легко заграбастали весь «банк», ловко перебрасывая друг другу козырей.\nВот только не учли, что наша игра записывается на камеру слежения." : '''Z łatwością wygraliśmy całą forsę, sprytnie rzucając \nsobie karty atutowe.\nO czym nie wiedzieliśmy, to o tym, \nże nasza rozgrywka była potajemnie nagrywana na monitoringu.''',
"[8]" : "[8]",
"Очень скоро нас вычислили и потребовали всё вернуть.\nЕстественно, с «моральной» компенсацией." : '''Wkrótce potem nas znaleźli i zażądali zwrotu \npieniędzy.\nRzecz jasna, z "moralną" rekompensatą.''',
"Затребованная сумма была слишком большой, а сроки – слишком короткие.\nНам ничего не оставалось, кроме как пойти на крайние меры." : '''Chcieli od nas zbyt dużo i nie dali nam żadnego \nczasu na znalezienie pieniędzy.\nNie mieliśmy wyboru \ni musieliśmy podjąć się gwałtownych środków.''',
"[9]" : "[9]",
"Я и Игорь попытались стащить несколько дорогостоящих часов в ювелирном магазине,\nно тут же были пойманы полицейским патрулём…" : '''Wraz z Igorem chcieliśmy ukraść wartościowe\n zegarki od jubilera,\nale natychmiast \nzłapał nas patrol policji...''',
"Чёрт!.." : '''Kurwa!...''',
"Теперь у меня не только проблемы с бандитами, но и с законом…" : '''Teraz mam problemy zarówno\n z gangsterami, jak i prawem...''',
"Брат, прости…" : '''Wybacz mi, bracie...''',
    }