translate dutch strings:
    #old '''Я должен что-то сделать по дому, чтобы она перестала обижаться на меня. Помыть посуду, закинуть бельё в стирку, пропылесосить в Зале.'''
    #new ''' '''
    old '''Вот и всё, я достаточно потрудился. Следует вновь поговорить с Мариной. Стоит сделать это на кухне или в коридоре.'''
    new '''Dat is het, ik heb genoeg gewerkt. Ik moet weer met Mary praten. Dat kan het beste in de keuken of op de gang.'''
    old '''Надо бы сходить в магазин, купить большой новый рюкзак и кое-какие продукты для поездки.'''
    new '''Ik moet naar een winkel in de buurt om een grote rugzak te kopen en wat eten voor onderweg.'''
    old '''Сегодня я уже достаточно «нагулялся». Следует почистить зубы, побриться и лечь спать.'''
    new '''Nah, ik ben genoeg buiten geweest voor vandaag. Ik moet mijn tanden poetsen, me scheren en gaan slapen.'''
    old '''Я срочно должен рассказать Игорю о ночном посетителе.'''
    new '''Ik moet Igor zo snel mogelijk vertellen over de nachtelijke bezoeker.'''
    #old '''Требование: Привязанность Марины (1)'''
    #new ''' '''
    old '''Полагаю, наши отношения с Мариной возвращаются в прежнее русло. Если я хочу, чтобы она снова доверяла мне, следует чаще проводить с ней время.'''
    new '''Ik denk dat ik op de goede weg ben met Mary. Als ik wil dat ze me weer vertrouwt, moet ik meer tijd met haar doorbrengen.'''
    old '''Я должен проверить СМС от друга.'''
    new '''Ik zou een berichtje van mijn vriendin moeten checken.'''
    old '''Лучшее, что я могу сделать сейчас, это просто наладить с ней отношения.'''
    new '''Het beste wat ik nu kan doen is proberen mijn relatie met haar te herstellen.'''
    old '''Пригласить Марину вечером в ресторан.'''
    new '''Neem Mary vanavond mee naar een restaurant.'''
    #old '''Требование: 6 Любовь Марины.'''
    #new ''' '''
    old '''Вернуться домой и подарить Марине кулон от себя.'''
    new '''Ga terug naar huis en geef het cadeau aan Mary zonder de agent te noemen.'''
    old '''Взять костюм с кровати.'''
    new '''Pak een pak van een bed.'''
    old '''Отправиться в магазин одежды и купить Марине подходящее платье.'''
    new '''Ga naar de kledingwinkel en koop een jurk voor Mary. Dat kun je beter 's ochtends of 's middags doen.'''
    old '''Заглянуть в комнату Марины.'''
    new '''Gluur in Mary's kamer.'''
    old '''Найти раздевалку Марины'''
    new '''Zoek Mary's kleedkamer.'''
    old '''Отправиться в ресторан с Мариной.'''
    new '''Ga met Mary naar een restaurant.'''
    #old '''Конец эпизода.'''
    #new ''' '''
    old '''Дождаться Марину днём в своей комнате.'''
    new '''Wacht op Mary in je kamer.'''
    old '''Дождаться новостей от Игоря. Если за день он так ничего и не напишет, написать ему самому.'''
    new '''Wacht op nieuws van Igor. Als hij binnen een dag niets schrijft, schrijf hem dan zelf.'''
    old '''Встретиться с Игорем в Парке Утром или Днём.'''
    new '''Ontmoet Igor 's ochtends of 's middags in het park.'''
    #old '''Сходить с Мариной в магазин одежды, и купить ей платье стоимостью не более 200 долларов.  Лучше всего это сделать утром или днём. '''
    #new ''' '''
    old '''Сесть на диван.'''
    new '''Ga op de bank zitten.'''
    #old '''Посетить спальню Марины ночью.'''
    #new ''' '''
    old '''Посетить спальню Марины сегодня ночью.'''
    new '''Bezoek vanavond Mary's slaapkamer.'''
    old '''Я дома. И я безумно хочу секса!'''
    new '''Ik ben thuis. En ik ben wanhopig om iemand te neuken!'''
    old '''Я умираю с голоду…'''
    new '''Ik sterf langzaam van de honger...'''
    old '''Я жутко голоден. Нужно поговорить об этом с Мариной.'''
    new '''Ik heb zo'n verdomde honger. Ik moet er met Mary over praten.'''
    old '''Брат намеревается отомстить. Если он что-то уготовил, значит так тому и быть.'''
    new '''Mijn broer is van plan om wraak te nemen. Als hij iets van plan is, is hij niet te stoppen.'''
    #old '''Судя по царапинам на полу, под унитазом расположен тайник. Неплохо было бы узнать, что там.  Для этого я должен расшатать конструкцию, но мне не хватает сил. Надо подкачаться, как бы смешно это не звучало.'''
    #new ''' '''
    old '''Купить белое вино в Супермаркете.'''
    new '''Koop witte wijn in de winkel.'''
    old '''Одиночество становится невыносимым. Стоило бы походить, да осмотреть своё временное жилище, пока я совсем не поехал крышей от гнетущих мыслей.'''
    new '''De eenzaamheid wordt ondraaglijk. Ik zou mijn tijdelijke huis eens beter moeten bekijken voordat ik helemaal gek word van de beklemmende gedachten.'''
    old '''Я на грани срыва…'''
    new '''Ik sta op het punt om te breken...'''
    #old '''Судя по царапинам на полу, под унитазом расположен тайник. Неплохо было бы узнать, что там. '''
    #new ''' '''
    old '''Вот и всё. Мои отношения с Мариной и Кристи достигли своего пика. Остаётся лишь наслаждаться жизнью и стараться не попадать в переделки.'''
    new '''Dat is het. Mijn relatie met Mary en Christy heeft zijn hoogtepunt bereikt. Het enige wat overblijft is van het leven genieten en proberen uit de problemen te blijven.'''
    #old '''Поспал и хватит.'''
    #new ''' '''
    old '''Мне удалось немного расшатать болты унитаза, но этого недостаточно. Теперь мне надо подкачаться ЕЩЁ СИЛЬНЕЕ!'''
    new '''Het is me gelukt om de wc-bouten een beetje los te draaien, maar dat is niet genoeg. Nu moet ik NOG HARDER TRAINEN!'''
    old '''Я практически расшатал болты унитаза. Остался последний рывок. Надо подкачаться. Сильнее. Намного сильнее. Чтоб аж вены на лбу выскочили.'''
    new '''Ik heb de bouten van het toilet bijna losgemaakt. Nog een laatste zetje. Ik moet trainen. Harder. Veel harder. Ik moet de aderen in mijn voorhoofd eruit laten springen.'''
    old '''Я в тюрьме…'''
    new '''Ik zit in een gevangenis...'''
    old '''Отодвинув унитаз, я нашёл таблетку неизвестного содержания. К ней прилагалась записка «Съешь меня, если хочешь выбраться». Судя по всему, я потратил время впустую.'''
    new '''Nadat ik het toilet had verplaatst, vond ik een pil met onbekende inhoud. Er zat een briefje bij waarop stond: "Eet me op als je eruit wilt komen." Blijkbaar had ik mijn tijd verspild.'''
    old '''Сходить в спальню Марины за её телефоном.'''
    new '''Ga naar Mary's slaapkamer en pak haar telefoon.'''
    old '''Принести Марине её телефон.'''
    new '''Breng Mary haar telefoon.'''
    #old '''Прочесть СМС от Игоря.'''
    #new ''' '''
    old '''Дождаться сообщения от Игоря.'''
    new '''Wacht op een bericht van Igor.'''
    #old '''Купить покорн и предложить Марине посмотреть сериал «Сладкий кексик». \nДополнительно: Накопить 150$ для перевода Игорю.'''
    #new ''' '''
    #old '''Требование: Привязанность Марины (2)'''
    #new ''' '''
    #old '''Нужно проникнуть в ванну, когда там будет Марина, и украсть её трусики. '''
    #new ''' '''
    old '''Вернуться домой.'''
    new '''Ga naar huis.'''
    old '''Найти резиновые перчатки'''
    new '''Zoek rubberen handschoenen.'''
    old '''Достать пистолет из мусорки вечером в парке'''
    new '''Pak een pistool uit een prullenbak in het park. Tijd: Avond.'''
    old '''Обсудить свой план побега с Игорем лично. Каждое утро он работает в парке, выполняя за меня предписание судьи.'''
    new '''Ik zou mijn ontsnappingsplan met Igor moeten bespreken. Elke ochtend werkt hij in het park, hij doet het gemeenschapswerk voor mij.'''
    #old '''Дождусь новостей от Игоря и тогда уж решу окончательно, валить из города, или принять свою участь и сдохнуть, как собака. '''
    #new ''' '''
    #old '''Как только у меня будет 150 долларов, попросить Марину перечислить деньги Игорю.'''
    #new ''' '''
    old '''Отбить свою «торговую точку» на углу Магазина. Мне нужен или помощник, или подручное средство против гопников.'''
    new '''Ik moet mijn "verkoopplek" bij de hoek van de winkel terugvechten. Ik heb iemand nodig om me te helpen of iets waarmee ik die idioten kan slaan.'''
    old '''Надо срочно посмотреть порно. Это успокоит меня на время. Время: Ночь'''
    new '''Ik zou wat porno moeten kijken. Dit zal me een tijdje kalmeren. Tijd: Nacht'''
    #old '''Заработать немного денег на продаже наркотиков. Если мне понадобится товар для сбыта, я всегда могу добыть новые закладки в Парке. '''
    #new ''' '''
    old '''Что ж, сегодня я уже никуда не денусь. Положу штаны в стирку и отсижусь дома.'''
    new '''Nou, ik denk dat ik vandaag nergens heen ga. Ik ga mijn broek in de was doen en blijf de hele dag thuis.'''
    #old '''Как только у меня будет 150 долларов, попросить Марину перечислить деньги Игорю. Нужно поговорить с ней на кухне.'''
    #new ''' '''
    #old '''Лучшее, что я сейчас могу сделать, это провести свой последний вечер с единственным человеком, которому я неравнодушен: следует купить красное вино и подобрать подходящий фильм.\nДиск с подходящим фильмом можно найти в зале.'''
    #new ''' '''
    #old '''Требование: Привязанность Марины (3)'''
    #new ''' '''
    old '''Спросить Марину про запертую дверь.'''
    new '''Mary vragen over de gesloten deur.'''
    #old '''Лечь спать. '''
    #new ''' '''
    old '''Проведать Игоря в Парке.'''
    new '''Ga naar Igor in het park.'''
    old '''Установить горшок с растением в коридоре. Сделать это следует или Утром, или Днём.'''
    new '''Een bloempot in de gang zetten. Dit moet 's ochtends of 's middags gebeuren.'''
    old '''Обменять трусики Кристи на горшок у Зудилы и Бубнилы.'''
    new '''Een broek ruilen voor een pot.'''
    #old '''Выяснить у Кэт (Ночной гостьи,, где именно удерживают Игоря. Для этого следует дождаться её ночью. '''
    #new ''' '''
    #old '''Если я не хочу проблем с офицером полиции, мне следует убирать в Парке каждый день. '''
    #new ''' '''
    #old '''Ну что тебе не понятно, [gg]? Просто полей цветы! '''
    #new ''' '''
    #old '''Пожалуй, мне ничего не остаётся, кроме как хорошенько выспаться. '''
    #new ''' '''
    old '''Украсть у Кристи трусики, пока она принимает ванну и обменять их на горшок у Зудилы и Бубнилы.'''
    new '''Christy's slipje stelen terwijl ze in bad zit en ruilen voor een pot.'''
    old '''Прежде чем разрабатывать план, следует придумать, как избавиться от липучего офицера полиции, но так, чтобы и Джеймс не пытался следить за мной.'''
    new '''Voordat ik een plan ontwikkel, moet ik uitzoeken hoe ik van de plakkerige politieagent afkom, maar zonder dat James me probeert te volgen.'''
    old '''Марина предложила мне прогулять уборку и провести это время с ней.'''
    new '''Mary vroeg me om het schoonmaken over te slaan en tijd met haar door te brengen.'''
    old '''Найти горшок для моего нового приятеля по имени [ep5_tree_name]. Надо у кого-нибудь поспрашивать. Или в магазине, или ещё где.'''
    new '''Zoek een pot voor mijn nieuwe maatje [ep5_tree_name]. Je moet het iemand vragen. Of in de winkel, of ergens anders.'''
    old '''Найти замену растению по имени Джими. Поискать его в парке.'''
    new '''Zoek een nieuwe plant voor Mary. Ik kan er in het park naar zoeken.'''
    old '''Купить слабительное и отдать его Марине.'''
    new '''Koop een laxeermiddel en geef het aan Mary.'''
    old '''Выйти из комнаты.'''
    new '''Verlaat de kamer.'''
    old '''Поговорить с Мариной.'''
    new '''Dat is het, ik heb genoeg gewerkt. Ik moet weer met Mary praten. Dat kan het beste in de keuken of op de gang.'''
    old '''Написать смс Игорю.'''
    new '''Schrijf een boodschap aan Igor.'''
    old '''Активировать входную верь в коридоре.'''
    new '''Activeer de voordeur in de gang.'''
    old '''Отправиться в гетто.'''
    new '''Ga naar het getto'''
    old '''Найти Игоря'''
    new '''Vind Igor'''
    old '''Купить два костюма: себе и Кэт.'''
    new '''Koop twee kostuums. Eén voor jou en één voor Cat.'''
    old '''Дождаться Кэт у себя в комнате.'''
    new '''Wacht op Cat in je kamer.'''
    old '''Переодеться в повседневную одежду у себя в комнате.'''
    new '''Trek in je kamer je gewone kleren aan.'''
    old '''Как только я буду готов вызволить Игоря, следует поговорить с Мариной Утром или Днём.'''
    new '''Als ik klaar ben om Igor te gaan redden, moet ik 's ochtends of 's middags met Mary praten.'''
    old '''Проверить Марину у себя в спальне.'''
    new '''Controleer Mary in je slaapkamer.'''
    #old '''Попрощаться с Мариной и Кристи, дождавшись их у входной двери в коридоре Вечером. '''
    #new ''' '''
    old '''Вернуться в свою комнату, дождавшись, пока Игорь взломает сейф.'''
    new '''Ga terug naar je kamer en wacht tot Igor de safe kraakt.'''
    old '''Проверить телефон'''
    new '''De telefoon controleren.'''
    #old '''Дождаться, когда никого не будет дома, и перебрать все комбинации. Уверен, через день-два такая возможность появится. '''
    #new ''' '''
    old '''Если я спрошу о Дне Рождении Марину, она наверняка обидится. Не хочу её огорчать. Снова. Узнаю эту информацию у Кристи, она точно помнит.'''
    new '''Als ik Mary naar haar verjaardag vraag, zal ze waarschijnlijk beledigd zijn. Ik wil haar niet van streek maken. Nogmaals. Ik krijg die informatie wel van Christie, ze weet het vast nog wel.'''
    old '''Сходить в спальню к Игорю и взять домашние вещи Марины.'''
    new '''Ga naar Igor's slaapkamer en pak Mary's huishoudspullen.'''
    old '''Теперь мне нужен пароль от сейфа, но я понятия не имею, как его разузнать. Надо спросить у Игоря, он мозг в нашей команде недотёп. Напишу ему завтра с утра.'''
    new '''Nu heb ik het wachtwoord van de kluis nodig, maar ik heb geen idee hoe ik eraan moet komen. Ik moet het aan Igor vragen, hij is het brein achter ons team van buitenbeentjes. Ik sms hem morgenochtend.'''
    #old '''Теперь я знаю предположительный пароль от сейфа. Нужно дождаться, когда никого не будет дома, и перебрать все комбинации. \nЧтобы с пользой для себя убить время, посмотрю с Мариной ужастик. '''
    #new ''' '''
    #old '''Требование: 4 Любовь Марины.'''
    #new ''' '''
    #old '''Отдать вещи Марине и надеть штаны. '''
    #new ''' '''
    old '''Поторопить Игоря.'''
    new '''Ik moet opschieten Igor.'''
    old '''Кинуть штаны в стиральную машину.'''
    new '''Stop je broek in de wasmachine.'''
    old '''Поговорить с Игорем в парке'''
    new '''Ik moet met Igor praten in het park en kijken of hij Masha's telefoon heeft kunnen hacken. Hij zal er morgenochtend zijn.'''
    old '''Полагаю, Марина уже помылась. Нужно искать её на кухне.'''
    new '''Ik denk dat Mary al gedoucht heeft. Ik moet naar de keuken.'''
    old '''Лечь спать.'''
    new '''Vandaag ben ik te moe, ik moet gewoon naar bed.'''
    old '''Написать СМС Игорю.'''
    new '''Schrijf een boodschap aan Igor.'''
    #old '''На сегодня с меня хватит, пора спать. '''
    #new ''' '''
    old '''Убедить Марину и Кристи отправиться в театр.'''
    new '''Overtuig Mary en Christie om naar het theater te gaan.'''
    #old '''Требование: 5 Любовь Марины.'''
    #new ''' '''
    old '''Проверить все комнаты, убедившись, что дома никого нет.'''
    new '''Controleer alle kamers en zorg ervoor dat er niemand thuis is.'''
    #old '''Встретиться с Игорем. '''
    #new ''' '''
    #old '''Спросить про билеты в театр у Зудилы и Бубнилы. '''
    #new ''' '''
    #old '''Дать Игорю 200 долларов для покупки взломщика сейфов. '''
    #new ''' '''
    old '''Я должен вставить диск в видео-проигрыватель.'''
    new '''Ik moet het schijfje in de videospeler stoppen.'''
    #old '''Следует обыскать комнату Марины и узнать, где именно она прячет свою «заначку». '''
    #new ''' '''
    old '''Поговорить с Зудилой и Бубнилой.'''
    new '''Praat met Itchy en Blabbermouth.'''
    #old '''Забрать билеты в театр у Зудилы и Бубнилы. '''
    #new ''' '''
    old '''Дождаться Игоря.'''
    new '''Wacht op Igor.'''
    #old '''Написать Игорю СМС.'''
    #new ''' '''
    old '''Вручить букет продавщице.'''
    new '''Geef het boeket aan de winkelbediende'''
    old '''Опробовать все комбинации цифр для открытия сейфа.'''
    new '''Probeer alle cijfercombinaties om de kluis te openen.'''
    old '''Принести Зудиле и Бубниле букет из роз. Нарвать цветы я смогу в парке. 12 штук будет предостаточно.'''
    new '''Ik moet Itchy en Blabbermouth een boeket rozen brengen. Ik kan de bloemen in het park plukken. 12 is genoeg.'''
    old '''Поговорить с Игорем в парке завтра Утром, узнав у него, смог он взломать телефон Маши или нет.'''
    new '''Ik moet met Igor praten in het park en kijken of hij Masha's telefoon heeft kunnen hacken. Hij zal er morgenochtend zijn.'''
    old '''Найти подходящее время для беседы. Поговорить с Кристи Днём в Комнате.'''
    new '''Kies het juiste moment om te praten. Praat met Christy in Kitchen, de volgende ochtend.'''
    old '''Обговорить с Кристи заказ Сьюзан.'''
    new '''Spreek met Christy over Susans verzoek.'''
    old '''Сходить на приём к Сьюзен и рассказать ей известную информацию о муже.'''
    new '''Ga naar Susans sessie en vertel haar bekende informatie over haar man.'''
    old '''Поговорить со Сьюзен по поводу работы, но прежде, мне нужно хорошенько отоспаться.'''
    new '''Spreek met Susan over werk, maar eerst heb ik een goede nachtrust nodig.'''
    #old '''Спросить Игоря как идут дела с замком Кристи.'''
    #new ''' '''
    old '''Проверить телефон.'''
    new '''De telefoon controleren.'''
    old '''Рассказать Кристи о походе к психологу.'''
    new '''Christy vertellen dat ze naar een psycholoog gaat.'''
    old '''Прочесть смс.'''
    new '''Controleer nieuwe SMS.'''
    old '''Приготовить салаты и бутерброды.'''
    new '''Kook wat salades en hamburgers.'''
    old '''Отправить Игорю ролик, где Кристи показывает стриптиз.'''
    new '''Stuur Igor een video waarop Christie een striptease uitvoert.'''
    old '''Отправить Игорю Видео с Кристи.'''
    new '''Stuur Igor een video met Christy.'''
    old '''Поговорить со Сьюзен по поводу работы.'''
    new '''Spreek met Susan over de baan.'''
    old '''Вывести из строя кондиционер Ночью, пока никто не видит.'''
    new '''Ik moet 's nachts met de airconditioner rommelen als niemand me kan zien.'''
    old '''Кристи обещала записать меня к психологу. Если я готов на «трепанацию мозга», мне следует поговорить с ней об этом завтра Днём.'''
    new '''Christy heeft beloofd een afspraak voor me te maken bij een psycholoog. Als ik klaar ben voor een 'hersenpanatie', moet ik daar morgenmiddag met haar over praten.'''
    old '''Отправиться на слежку. Лучше всего начать это делать с самого утра, начав с дома Сьюзен.'''
    new '''Ga naar buiten om te spioneren. Het beste is om vroeg in de ochtend te beginnen, bij Susan thuis.'''
    old '''Встретиться с Зудилой и Бубнилой, чтобы взять у них кофе «Релакс».'''
    new '''Ontmoet Itcher en Mumbler om koffie te halen 'Relax'.'''
    #old '''@@@@@@@@Конец рута Кристи для эпизода 1.0'''
    #new ''' '''
    old '''Сьюзен ведёт тебя странно, но раз уж я дал слово, нужно довести дело до конца и выяснить, изменяет ей муж или нет. Продолжу слежку завтра Утром.'''
    new '''Susan gedraagt zich vreemd tegenover jou, maar omdat ik mijn woord heb gegeven, moet ik doorgaan en uitzoeken of haar man vreemdgaat of niet. Ik ga morgenochtend verder met mijn surveillance.'''
    old '''Продолжить следить за офицером. Как и в предыдущий раз, лучше всего это делать Утром, когда полицейский выходит из дома.'''
    new '''Ik moet de politieagent goed in de gaten houden. Net als de vorige keer kan ik dat het beste 's ochtends doen, wanneer hij zijn huis verlaat.'''
    #old '''Теперь мне нужно уложить приготовленные бутерброды в корзину и можно отправляться на пикник с Кристи.\nБутерброды лежат в холодильнике.'''
    #new ''' '''
    old '''Вернуться к Кристи.'''
    new '''Kom terug naar Christie.'''
    old '''Утром или Днём сходить к психологу на приём.'''
    new '''Ga 's ochtends of 's middags naar een psycholoog voor een afspraak.'''
    old '''Купить продукты для пикника.'''
    new '''Ik moet eten kopen voor de picknick.'''
    old '''Вернуться в комнату.'''
    new '''Ga terug naar de kamer.'''
    old '''Купить подарочное издание «Дон Кихот» Мигеля Де Сервантеса.'''
    new '''Koop een cadeau-editie van "Don Quichot" van Miguel De Cervantes.'''
    old '''Купить кофе в магазине.'''
    new '''Koffie kopen in de winkel.'''
    #old '''Я нашёл, где взять кофе для Кристи, но чтобы получить его, мне надо помочь Зудиле и Бубниле «соблазнить» продавщицу в магазине. Для этого я должен:\n1, {s}Принять душ{/s} \n2, {s}Почистить зубы{/s} \n3, {s}Взять у Марины какие-нибудь духи{/s} \n4, {s}Найти мой старый школьный костюм, чтобы выглядеть презентабельно.{/s}'''
    #new ''' '''
    old '''Отправиться в магазин одежды. Желательно днём. Следует отвлечь продавщицу и проникнуть в туалетную комнату.'''
    new '''Ik moet langs de kledingwinkel. Bij voorkeur overdag. Ik moet de verkoper afleiden en naar het toilet gaan.'''
    old '''Купить реферат по «Обществознанию» в интернете.'''
    new '''Koop online een essay over sociale studies.'''
    old '''Сегодня я слишком устал, нужно просто лечь спать.'''
    new '''Vandaag ben ik te moe, ik moet gewoon naar bed.'''
    old '''Найти воду на полках магазина, чтобы привести продавщицу в порядок.'''
    new '''Water vinden op de winkelschappen om de verkoopster weer tot leven te wekken.'''
    old '''Отправиться в Гетто Утром или Днём с плакатом, полученным от Зудилы и Бубнилы.'''
    new '''Ga 's ochtends of 's middags naar het getto met een poster die je van Mumbler en Itchy hebt gekregen.'''
    old '''Заснять Кристи в Душе, когда она моется или Ночью в её комнате, во время переодевания.'''
    new '''Ik zou een video moeten maken van Christie terwijl ze een douche neemt of zich uitkleedt voordat ze naar bed gaat.'''
    old '''Подобрать подходящее время для беседы. Поговорить с Кристи Утром на Кухне.'''
    new '''Kies het juiste moment om te praten. Praat met Christy in Kitchen, de volgende ochtend.'''
    old '''Теперь я могу отправиться к психологу, но сперва мне следует поговорить с Игорем и попросить его помочь с замком Кристи.'''
    new '''Nu kan ik naar de psychiater gaan, maar eerst moet ik met Igor praten en hem vragen te helpen met Christies slot.'''
    old '''Сначала поговорить с Игорем, а после отправиться в библиотеку и продолжить написание реферата по теме «Обществознание».'''
    new '''Praat eerst met Igor en ga dan naar de bibliotheek om verder te gaan met het schrijven van het opstel voor Maatschappijleer.'''
    old '''Отправиться в комнату Кристи.'''
    new '''Ga naar Christy's kamer.'''
    old '''Сходить к Игорю к Парк и попросить его взломать телефон продавщицы.'''
    new '''Ik moet naar het park komen en met Igor praten. Hij weet hoe ik de telefoon moet hacken.'''
    #old '''Отправиться в библиотеку Утром или Днём, чтобы составить реферат по теме «Обществознании».'''
    #new ''' '''
    #old '''@@@@@@@@Конец рута Кристи для эпизода [version_now]'''
    #new ''' '''
    old '''Отдать Кристи реферат.'''
    new '''Geef het essay aan Christy.'''
    old '''Поговорить с Кристи Утром в Зале.'''
    new '''Praat 's ochtends met Christy in de hal.'''
    old '''Отправиться в свою комнату.'''
    new '''Ga naar je kamer.'''
    old '''Купить любой костюм для ролевых игр.'''
    new '''Koop een kostuum voor rollenspellen.'''
    old '''Отдать костюм Кристи. Сделать это следует Утром или Днём.'''
    new '''Geef het kostuum aan Christie. Ik moet het 's ochtends of 's middags doen.'''
    old '''Проведать Игоря в Парке и показать ему запись с продажным копом.'''
    new '''Ik moet Igor opzoeken in het park en hem de opname met een corrupte agent laten zien.'''
    old '''Поговорить с Кристи Утром на Кухне.'''
    new '''Kies het juiste moment om te praten. Praat met Christy in Kitchen, de volgende ochtend.'''
    old '''Пора спать. Утром и узнаю, получилось у меня или нет.'''
    new '''Tijd om te slapen. Morgenochtend weet ik of ik iets heb kunnen opnemen.'''
    old '''Надо во всём сознаться и объяснить сложившуюся ситуацию!'''
    new '''Ik moet haar vertellen over de situatie waarin ik me bevind!'''
    #old '''@@@@@@@@Конец рута Кристи для эпизода 0.8.9'''
    #new ''' '''
    old '''Установить мобильный телефон возле телевизора в Зале Ночью, пока никто не видит.'''
    new '''Tijd om mijn telefoon te laten opnemen bij de tv 's avonds in de woonkamer, als iedereen slaapt.'''
    old '''Провести очередной сеанс с психологом, живущей в соседнем доме. Она принимает только Утром или Днём.'''
    new '''Heb nog een sessie met de buurpsycholoog. Ze ontvangt alleen 's ochtends of 's middags bezoek.'''
    old '''Пока не ясно, как скоро мы поймаем офицера на измене жене, зато можно запечатлеть его «грязные» поступки, которые, вероятно, нам тоже пригодятся.'''
    new '''Het is nog niet duidelijk hoe snel we de agent zullen betrappen op het bedriegen van zijn vrouw, maar we kunnen zijn "vuile" acties filmen, wat waarschijnlijk ook nuttig voor ons zal zijn.'''
    old '''Сходить в магазин и купить костюм Харли Квин для Кристи.'''
    new '''Ga naar de winkel en koop een Harley Quinn kostuum voor Christy.'''
    old '''Дождаться завтра и отдать Кристи реферат по «Обществознанию».'''
    new '''Wacht tot morgen en geef Christie het opstel over Maatschappijleer.'''
    old '''Поговорить с Кристи на следующий день, возможно я снова пригожусь ей для какого-нибудь «дела». Думаю лучше обратиться к ней прямо самого утра.'''
    new '''De volgende dag met Christy praten, misschien heb ik weer iets aan haar voor een of andere 'zaak'. Ik denk dat het het beste is om 's ochtends contact met haar op te nemen.'''
    old '''Если я ГОТОВ выдвинуться на слежку за офицером - отдать Кристи её костюм Харли Квин.'''
    new '''Als ik GEREED ben om de agent te gaan bespioneren - geef Christy haar Harley Quinn kostuum.'''
    #old '''Я нашёл, где взять кофе для Кристи, но чтобы получить его, мне надо помочь Зудиле и Бубниле «соблазнить» продавщицу в магазине. Для этого я должен: \n1, Принять душ \n2, Почистить зубы \n3, Взять у Марины какие-нибудь духи \n4, Найти мой старый школьный костюм, чтобы выглядеть презентабельно.'''
    #new ''' '''
    old '''Наслаждаться отношениями с Кристи'''
    new '''Geniet van je relatie met Christie'''
    #old '''Забрать у Зудилы и Бубнилы причитающуюся награду. '''
    #new ''' '''
    old '''Сходить на сеанс к Сьюзан.'''
    new '''Ga naar een sessie met Susan.'''
    old '''Обсудить предложение Сьюзан с Кристи.'''
    new '''Bespreek Susans suggestie met Christy.'''
    old '''Поговорить со Сьюзен.'''
    new '''Praat met Susan.'''
    old '''Открыть дверь Кристи.'''
    new '''Open Christie's deur.'''
    old '''Завершить реферат по «Обществознанию».'''
    new '''Maak je opstel voor Maatschappijleer af'''
    old '''Подарить Кристи книгу «Дона Кихот» Мигеля Де Сервантеса.'''
    new '''Geef Christie een boek "Don Quixote" van Miguel De Cervantes.'''
    #old '''Отправиться к Сьюзен и показать ей доказательства измены мужа. '''
    #new ''' '''
    old '''Отправить фотку Кристи Игорю.'''
    new '''Stuur Christie's foto naar Igor.'''
    old '''Купить отвёртку в Магазине.'''
    new '''Koop een schroevendraaier in de winkel.'''
    old '''Отдать Кристи реферат по «Обществознанию». Лучше сделать это с утра.'''
    new '''Geef Christie het opstel voor Maatschappijleer'''
    old '''Купить красивую корзину, куда можно будет положить бутерброды и салат. Но что-то мне подсказывает, в магазине я вряд ли её смогу найти.'''
    new '''Nu moet ik een mooi mandje kopen om boterhammen en salade in te doen, maar iets zegt me dat ik dat niet in een winkel zal kunnen vinden.'''
    old '''Поговорить с Кристи о пикнике.'''
    new '''Praat met Christie over de picknick.'''
    old '''Обсудить с Кэт, куда она уходит ночью.'''
    new '''Praat met Kat over waar ze 's nachts naartoe gaat.'''
    old '''Купить чёрные очки.'''
    new '''Koop een zwarte bril.'''
    old '''Проследить за Кэт вечером у входа в дом.'''
    new '''Wacht vanavond op Kat bij de veranda.'''
    old '''Пошалить с Кэт'''
    new '''Maak plezier met Kat.'''
    #old '''@@@@Конец рута Кэт для эпизода 6'''
    #new ''' '''
    #old '''Вполне вероятно, что в Парке, где я роюсь в поисках закладки, я смогу поймать какую-нибудь заблудшую лягушку. '''
    #new ''' '''
    #old '''Активировать отверстие в стене при наступлении ночи. '''
    #new ''' '''
    old '''Теперь мне нужно выждать момент, когда Кристи не будет дома и начать пилить стену. Лучше всего делать это Вечером.'''
    new '''Nu moet ik wachten tot Christy niet thuis is en beginnen met het zagen van de muur. De beste tijd om dit te doen is 's avonds.'''
    old '''Нужно зайти к Кристи в комнату, когда её там нет, и измерить место на стене, куда она крепит свой фалос.'''
    new '''Ik moet naar Christies kamer gaan als ze er niet is en wat metingen op de muur doen.'''
    old '''Подождать 2 дня, прежде чем я смогу получить линейку у Кристи.'''
    new '''Wacht 2 dagen voordat ik het meetlint van Christy kan krijgen.'''
    #old '''Ночные услады Кристи с фалосом не дают мне покоя. Было бы замечательно заменить её секс-игрушку на свой член, но как это сделать? Для начала нужно купить резак для стены, чтобы вырезать отверстие в месте куда Кристи клеит фалос. '''
    #new ''' '''
    old '''Попросить у Кристи линейку.'''
    new '''Vraag Christie om een liniaal.'''
    old '''Теперь я могу забавляться с этой дырой в стене хоть каждую ночь...'''
    new '''Nu kan ik elke avond met dit gat in de muur spelen...'''
    old '''Отдать лягушку Кристи, чтобы та выменяла её на линейку-рулетку у «подружки».'''
    new '''Geef de kikker aan Christy zodat ze die kan ruilen voor haar meetlint van haar niet al te beste vriendin.'''
    old '''Зайти в спальню Кристи ночью.'''
    new '''s Nachts naar Christies slaapkamer gaan'''
    old '''Надеюсь она чувствует себя лучше.'''
    new '''Ik hoop dat ze zich beter voelt.'''
    old '''Нужно попробовать "Пошалить" с Кристи днём, а не только ночью.'''
    new '''Ik moet proberen te "Spelen" met Christie tijdens de dag, niet alleen 's nachts.'''
    old '''Отправиться в парк'''
    new '''Ga naar het park'''
    #old '''Марина уже на грани. Пожалуй, мне стоит ещё раз прогуляться и вернуться домой поздно ночью, прежде чем я позволю ей вынуть анальную пробку. '''
    #new ''' '''
    old '''Зайти к Марине в спальню.'''
    new '''Ga naar de slaapkamer van Mary.'''
    old '''Отправить Марине СМС.'''
    new '''Stuur een sms naar Mary.'''
    old '''@@@Конец ивента'''
    new '''Einde gebeurtenis voor aflevering [version_now]'''
    old '''Купить Марине анальную пробку в интернет-магазине и подарить ей.'''
    new '''Koop een anaalplug in de online winkel en geef hem aan Mary.'''
    old '''Прождать какое-то время, доведя Марину до экстаза. Чтобы ускорить стимуляцию, мне стоит избегать Марину, и возвращаться домой поздно ночью.'''
    new '''Wacht even om Mary in extase te brengen. Om de stimulatie te versnellen, moet ik Mary vermijden en 's avonds laat thuiskomen.'''
    #old '''ПРОДОЛЖАТЬ ждать какое-то время, доведя Марину до экстаза. Чтобы ускорить стимуляцию, мне стоит избегать Марину, и возвращаться домой поздно ночью. '''
    #new ''' '''
    old '''Дождаться появления офицера полиции через 2-3 дня вечером в коридоре.'''
    new '''Wacht tot de politieagent over 2-3 dagen 's avonds in de gang verschijnt.'''
    old '''Прождать 2-3 дня, прежде чем полицейский снова явится в гости. Приходит он в основном вечером.'''
    new '''Wacht 2-3 dagen voordat de politieagent weer op bezoek komt. Hij komt meestal 's avonds.'''
    #old '''@@@Конец ивента для эпизода 0.8.5'''
    #new ''' '''
    old '''@@@Конец ивента для эпизода [version_now]'''
    new '''Einde gebeurtenis voor aflevering [version_now]'''
    old '''Отдать перцовый баллончик Марине.'''
    new '''Geef een pepperspray aan Mary'''
    old '''Всё слишком хорошо оборачивается для меня, чтобы жить припеваючи. Стоит быть на чеку. Мне кажется в течении 2-3 дней может произойти что-то, что вновь напомнит о прежних временах.'''
    new '''Het gaat gewoon te goed. Ik moet alert blijven. Ik denk dat over 2-3 dagen mijn verleden me kan gaan achtervolgen.'''
    old '''Купить перцовый баллончик для Марины.'''
    new '''Koop pepperspray voor Mary'''




    old '''Сходить с Мариной в магазин одежды, и купить ей платье стоимостью не более 200 долларов.  Лучше всего это сделать утром или днём. '''

    new '''Ga naar de kledingwinkel en koop een jurk voor Mary. Dat kun je beter 's ochtends of 's middags doen. '''

    old '''Купить покорн и предложить Марине посмотреть сериал «Сладкий кексик». \nДополнительно: Накопить 150$ для перевода Игорю.'''

    new '''Koop popcorn en nodig Marina uit om naar de tv-serie "Sweet Fruitcake" te kijken. \nOptioneel: Spaar 150$ om naar Igor te sturen. '''

    old '''Лучшее, что я сейчас могу сделать, это провести свой последний вечер с единственным человеком, которому я неравнодушен: следует купить красное вино и подобрать подходящий фильм.\nДиск с подходящим фильмом можно найти в зале.'''

    new '''Het beste wat ik nu kan doen is mijn laatste avond doorbrengen met de enige persoon om wie ik geef; ik moet rode wijn kopen en een geschikte film uitzoeken. '''

    old '''Теперь я знаю предположительный пароль от сейфа. Нужно дождаться, когда никого не будет дома, и перебрать все комбинации. \nЧтобы с пользой для себя убить время, посмотрю с Мариной ужастик. '''

    new '''Nu weet ik het wachtwoord van de kluis. Ik moet wachten tot er niemand thuis is en alle combinaties proberen. \nSnOm de tijd te doden ga ik een horrorfilm kijken met Mary. '''

    old '''Теперь мне нужно уложить приготовленные бутерброды в корзину и можно отправляться на пикник с Кристи.\nБутерброды лежат в холодильнике.'''

    new '''Nu moet ik alleen nog de boterhammen in de mand doen en dan kunnen we met Christy gaan picknicken. '''

    # old '''Я нашёл, где взять кофе для Кристи, но чтобы получить его, мне надо помочь Зудиле и Бубниле «соблазнить» продавщицу в магазине. Для этого я должен: \n1, Принять душ \n2, Почистить зубы \n3, Взять у Марины какие-нибудь духи \n4, Найти мой старый школьный костюм, чтобы выглядеть презентабельно.'''

    # new '''Ik heb een plek gevonden waar ik Christy's koffie kan krijgen, maar daarvoor moet ik Itcher en Mumbler helpen de verkoopster te 'verleiden'. Om dat te doen, moet ik: \n1) Een douche nemen. \n2) Mijn tanden poetsen. \n3) Parfum halen bij Mary. \n4) Mijn oude schoolkleren vinden om er toonbaar uit te zien. '''

    old '''Отправиться в библиотеку Утром или Днём, чтобы составить реферат по теме «Обществознании».'''

    new '''Ga 's ochtends of 's middags naar de bibliotheek om een essay over sociale studies te schrijven. '''

    old '''Забрать у Зудилы и Бубнилы причитающуюся награду. '''

    new '''Neem je beloning aan van Mumbler en Itchy. '''

    old '''Отправиться к Сьюзен и показать ей доказательства измены мужа. '''

    new '''Ik moet naar Susan gaan en haar het bewijs van de ontrouw van haar man laten zien. '''

    old '''Вполне вероятно, что в Парке, где я роюсь в поисках закладки, я смогу поймать какую-нибудь заблудшую лягушку. '''

    new '''Ik denk dat ik een verdwaalde kikker kan vangen in het park, waar ik vroeger mijn voorraad haalde. '''

    old '''Активировать отверстие в стене при наступлении ночи. '''

    new '''s Avonds een gat in de muur maken. '''

    old '''Ночные услады Кристи с фалосом не дают мне покоя. Было бы замечательно заменить её секс-игрушку на свой член, но как это сделать? Для начала нужно купить резак для стены, чтобы вырезать отверстие в месте куда Кристи клеит фалос. '''

    new '''Christy's nachtspelletjes met een dildo achtervolgen me. Het zou geweldig zijn om haar seksspeeltje te vervangen door mijn pik, maar hoe doe ik dat? Eerst moet ik een muursnijder kopen en voorzichtig een gat snijden op de plek waar Christy de dildo plakt. '''

    old '''Марина уже на грани. Пожалуй, мне стоит ещё раз прогуляться и вернуться домой поздно ночью, прежде чем я позволю ей вынуть анальную пробку. '''

    new '''Mary staat al op scherp. Misschien moet ik nog een wandeling maken en 's avonds laat thuiskomen voordat ik haar de buttplug eruit laat halen. '''

    old '''ПРОДОЛЖАТЬ ждать какое-то время, доведя Марину до экстаза. Чтобы ускорить стимуляцию, мне стоит избегать Марину, и возвращаться домой поздно ночью. '''

    new '''Blijf een tijdje wachten om Mary in extase te brengen. Om de stimulatie te versnellen, moet ik Mary vermijden en 's avonds laat naar huis gaan. '''





    old '''Судя по царапинам на полу, под унитазом расположен тайник. Неплохо было бы узнать, что там.  Для этого я должен расшатать конструкцию, но мне не хватает сил. Надо подкачаться, как бы смешно это не звучало.'''
    new '''Aan de krassen op de vloer te zien, zit er een voorraad onder het toilet. Ik zou graag willen weten wat daaronder zit.  Om dat te doen moet ik de structuur losmaken, maar ik ben niet sterk genoeg. Ik moet sporten, hoe belachelijk dat ook klinkt.'''

    old '''Судя по царапинам на полу, под унитазом расположен тайник. Неплохо было бы узнать, что там. '''
    new '''À en juger par les rayures sur le sol, il y a une cachette sous les toilettes. Ce serait bien de savoir ce qu'il y a là-dessous.'''
